version: '3.9'

services:

  mysql:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./dump-project-hibernate-final.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - geo-network

  redis:
    image: redis:latest
    container_name: redis-db
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - geo-network

  ### TODO добавить postgres

volumes:
  mysql-data:
  redis-data:

networks:
  geo-network:
    driver: bridge